version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "14:28"
      timezone: "America/New_York"
    assignees:
      - "sei-aschlackman"
      - "sei-noconnor"
      - "sei-chershberger"
